### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by minhdoboi** [illim/fserve#1]
INFO add player 174929935950225431
DEBUG line 1;8;1;0
DEBUG receive message with header 1;8;1;0
INFO set name badsleep
DEBUG line 
DEBUG Disconnected player 174929935950225431
INFO add player 4253378732877690173
multiple connections lead to a crash

DEBUG line 1;8;1;0
DEBUG receive message with header 1;8;1;0
INFO set name badsleep
DEBUG line 5;95;2;0
DEBUG receive message with header 5;95;2;0
DEBUG line 5;97;3;0
DEBUG receive message with header 5;97;3;0
Traceback (most recent call last)
main.nim(9)              main
asyncdispatch.nim(1676)  runForever
asyncdispatch.nim(1063)  poll
system.nim(2515)         cb
asyncdispatch.nim(245)   fail
asyncdispatch.nim(1303)  cb
asyncdispatch.nim(245)   fail
asyncdispatch.nim(1303)  cb
asyncdispatch.nim(245)   fail
asyncdispatch.nim(1303)  cb
asyncdispatch.nim(245)   fail
asyncdispatch.nim(334)   :anonymous
Error: unhandled exception: Operation timed out
  recvInto's lead up to read of failed Future:
    Traceback (most recent call last)
    main.nim(9)              main
    asyncdispatch.nim(1676)  runForever
    asyncdispatch.nim(1063)  poll
    system.nim(2515)         cb
    asyncdispatch.nim(243)   fail
  recvLineInto's lead up to read of failed Future:
    Traceback (most recent call last)
    main.nim(9)              main
    asyncdispatch.nim(1676)  runForever
    asyncdispatch.nim(1063)  poll
    system.nim(2515)         cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1291)  cb
    asyncnet.nim(211)        recvLineIntoIter
    asyncdispatch.nim(292)   read
  recvLine's lead up to read of failed Future:
    Traceback (most recent call last)
    main.nim(9)              main
    asyncdispatch.nim(1676)  runForever
    asyncdispatch.nim(1063)  poll
    system.nim(2515)         cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1303)  cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1291)  cb
    asyncnet.nim(436)        recvLineIter
    asyncdispatch.nim(292)   read
  processPlayer's lead up to read of failed Future:
    Traceback (most recent call last)
    main.nim(9)              main
    asyncdispatch.nim(1676)  runForever
    asyncdispatch.nim(1063)  poll
    system.nim(2515)         cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1303)  cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1303)  cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1291)  cb
    state.nim(116)           processPlayerIter
    asyncdispatch.nim(292)   read [Exception]

**Comment by minhdoboi** [comment]
maybe linked to https://github.com/nim-lang/Nim/issues/3964

**Comment by illim** [comment]
upgrading to use nim 0.14.2
Have to check if this occurs again.

**Comment by illim** [comment]
happened again

```
   INFO set name Vadim
DEBUG line 
DEBUG Disconnected player 7718895017437399251
INFO add player 3635879454393978813
DEBUG line 1;4;1;0
DEBUG receive message with header 1;4;1;0
INFO set name John
Traceback (most recent call last)
main.nim(9)              main
asyncdispatch.nim(1676)  runForever
asyncdispatch.nim(1063)  poll
system.nim(2515)         cb
asyncdispatch.nim(245)   fail
asyncdispatch.nim(1303)  cb
asyncdispatch.nim(245)   fail
asyncdispatch.nim(1303)  cb
asyncdispatch.nim(245)   fail
asyncdispatch.nim(1303)  cb
asyncdispatch.nim(245)   fail
asyncdispatch.nim(334)   :anonymous
Error: unhandled exception: Operation timed out
  recvInto's lead up to read of failed Future:
    Traceback (most recent call last)
    main.nim(9)              main
    asyncdispatch.nim(1676)  runForever
    asyncdispatch.nim(1063)  poll
    system.nim(2515)         cb
    asyncdispatch.nim(243)   fail
  recvLineInto's lead up to read of failed Future:
    Traceback (most recent call last)
    main.nim(9)              main
    asyncdispatch.nim(1676)  runForever
    asyncdispatch.nim(1063)  poll
    system.nim(2515)         cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1291)  cb
    asyncnet.nim(211)        recvLineIntoIter
    asyncdispatch.nim(292)   read
  recvLine's lead up to read of failed Future:
    Traceback (most recent call last)
    main.nim(9)              main
    asyncdispatch.nim(1676)  runForever
    asyncdispatch.nim(1063)  poll
    system.nim(2515)         cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1303)  cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1291)  cb
    asyncnet.nim(436)        recvLineIter
    asyncdispatch.nim(292)   read
  processPlayer's lead up to read of failed Future:
    Traceback (most recent call last)
    main.nim(9)              main
    asyncdispatch.nim(1676)  runForever
    asyncdispatch.nim(1063)  poll
    system.nim(2515)         cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1303)  cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1303)  cb
    asyncdispatch.nim(245)   fail
    asyncdispatch.nim(1291)  cb
    state.nim(116)           processPlayerIter
    asyncdispatch.nim(292)   read [Exception]

```

**Comment by illim** [comment]
abandonned nim version
